name: Build and Push Docker image to Amazon ECR 

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Login manual no Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 100527548163.dkr.ecr.us-east-1.amazonaws.com

    - name: Create ECR repository if not exist
      run: |
        aws ecr describe-repositories --repository-names servicoproducao-repo --region us-east-1 || \
        aws ecr create-repository --repository-name servicoproducao-repo --region us-east-1

    - name: Build Docker image
      run: |
        docker build -f Api/Dockerfile -t servicoproducao:${{ env.IMAGE_TAG }} .

    - name: Tag Docker image
      run: |
        docker tag servicoproducao:${{ env.IMAGE_TAG }} 100527548163.dkr.ecr.us-east-1.amazonaws.com/servicoproducao-repo:${{ env.IMAGE_TAG }}

    - name: Push to Amazon ECR
      run: |
        docker push 100527548163.dkr.ecr.us-east-1.amazonaws.com/servicoproducao-repo:${{ env.IMAGE_TAG }}
